# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: secure_chat.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'secure_chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11secure_chat.proto\x12\nsecurechat\"7\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x12\n\npublic_key\x18\x02 \x01(\t\"Y\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12#\n\x05users\x18\x03 \x03(\x0b\x32\x14.securechat.UserInfo\"0\n\x08UserInfo\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x12\n\npublic_key\x18\x02 \x01(\t\"j\n\x0b\x43hatMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x11\n\trecipient\x18\x02 \x01(\t\x12\x19\n\x11\x65ncrypted_content\x18\x03 \x01(\t\x12\n\n\x02iv\x18\x04 \x01(\x0c\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x32\x9b\x01\n\nSecureChat\x12\x44\n\nChatStream\x12\x17.securechat.ChatMessage\x1a\x17.securechat.ChatMessage\"\x00(\x01\x30\x01\x12G\n\x08Register\x12\x1b.securechat.RegisterRequest\x1a\x1c.securechat.RegisterResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secure_chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=33
  _globals['_REGISTERREQUEST']._serialized_end=88
  _globals['_REGISTERRESPONSE']._serialized_start=90
  _globals['_REGISTERRESPONSE']._serialized_end=179
  _globals['_USERINFO']._serialized_start=181
  _globals['_USERINFO']._serialized_end=229
  _globals['_CHATMESSAGE']._serialized_start=231
  _globals['_CHATMESSAGE']._serialized_end=337
  _globals['_SECURECHAT']._serialized_start=340
  _globals['_SECURECHAT']._serialized_end=495
# @@protoc_insertion_point(module_scope)
